server:
  port: 9000

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: post
    password: 1234
    
mybatis:
  type-aliases-package: com.example.post.model
  mapper-locations:
  - classpath:mapper/**/*.xml